### Broadcasting

In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr1 = arr/10

In [3]:
arr1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [4]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
slice_arr = arr[0:6]

In [8]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
slice_arr[:] = 555

In [10]:
slice_arr

array([555, 555, 555, 555, 555, 555])

In [11]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

##### Copy of Array

In [12]:
arr_copy  = arr.copy()

In [13]:
arr_copy [:]=1000

In [14]:
arr_copy 

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [15]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [16]:
arr[0:6]=[0,1,2,3,4,5]

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Conditional Selection

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
bool_arr = arr>4

In [20]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [22]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr/arr

<ipython-input-26-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

not a number-nan

In [27]:
1/arr

<ipython-input-27-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### Append

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a = np.append(a,[[21,22,23]],axis=0)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23]])

In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a_col = np.array([[34,35,36]]).reshape(3,1)
a_col

array([[34],
       [35],
       [36]])

In [32]:
np.append(a,a_col,axis=1)

array([[ 1,  2,  3, 34],
       [ 4,  5,  6, 35],
       [ 7,  8,  9, 36]])

### Insert

In [33]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.insert(b,3,[15,13,12],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [15, 13, 12]])

In [35]:
np.insert(b,1,[15,13,12],axis=0)

array([[ 1,  2,  3],
       [15, 13, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [36]:
np.insert(b,1,[15,13,12],axis=1)

array([[ 1, 15,  2,  3],
       [ 4, 13,  5,  6],
       [ 7, 12,  8,  9]])

### Matrix

In [37]:
x = np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
x.shape

(3, 3)

In [39]:
x.size

9

In [40]:
x[2,1]=-7

In [41]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr[2,1]=-7

In [44]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [45]:
x*x

matrix([[ 30,  -9,  42],
        [ 66,  -9,  96],
        [ 42, -84,  60]])

In [46]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [47]:
arr@arr

array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

#### Matrix Operations

In [48]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [49]:
np.linalg.det(x)

-90.0

In [50]:
np.linalg.matrix_rank(x)

3

In [51]:
np.linalg.inv(x)

matrix([[-0.96666667,  0.43333333,  0.03333333],
        [-0.06666667,  0.13333333, -0.06666667],
        [ 0.7       , -0.23333333,  0.03333333]])

#### &&&&&