In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5,6]

In [3]:
x

[1, 2, 3, 4, 5, 6]

In [4]:
type(x)

list

In [5]:
y = np.array(x)

In [6]:
y

array([1, 2, 3, 4, 5, 6])

In [7]:
y = np.array((1,2,3,4,5))

In [8]:
y

array([1, 2, 3, 4, 5])

In [9]:
x2 = (1,2,3,4,5)

In [10]:
y = np.array(x2)
y

array([1, 2, 3, 4, 5])

In [11]:
x = [1,2,'NIELIT',78]

In [12]:
y = np.array(x)

In [13]:
y

array(['1', '2', 'NIELIT', '78'], dtype='<U11')