In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5,6]

In [3]:
x

[1, 2, 3, 4, 5, 6]

In [4]:
type(x)

list

In [5]:
y = np.array(x)

In [6]:
y

array([1, 2, 3, 4, 5, 6])

In [7]:
y = np.array((1,2,3,4,5))

In [8]:
y

array([1, 2, 3, 4, 5])

In [9]:
x2 = (1,2,3,4,5)

In [10]:
y = np.array(x2)
y

array([1, 2, 3, 4, 5])

In [11]:
x = [1,2,'NIELIT',78]

In [12]:
y = np.array(x)

In [13]:
y

array(['1', '2', 'NIELIT', '78'], dtype='<U11')

In [5]:
np.linspace(start=0,stop=20,num=10,endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

In [3]:
#Endpoint
np.linspace(start=0,stop=20,num=10,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [4]:
#retstep
np.linspace(start=0,stop=20,num=10,endpoint=False,retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [6]:
np.arange(start=1,stop=10,step=2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Create 3*3 array

In [8]:
z = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
y = np.array(z)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Reshaping

In [14]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
x.reshape((5,1))

ValueError: cannot reshape array of size 10 into shape (5,1)

### Slicing

In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.

In [20]:
s = slice(2,7)

In [21]:
a[s]

array([2, 3, 4, 5, 6])

In [22]:
s = slice(2,7,2)

In [23]:
a[s]

array([2, 4, 6])

In [24]:
a[2:7]

array([2, 3, 4, 5, 6])

In [25]:
a[2:7:2]

array([2, 4, 6])

### Random Number Generation 

In [26]:
np.random.rand(5)

array([0.1372174 , 0.38056623, 0.7324382 , 0.94237535, 0.44274723])

In [27]:
np.random.randn(5,4)

array([[-1.18513445,  0.37520855, -1.07098538, -1.04720217],
       [-0.03195892, -0.15307922, -1.46911974,  0.41400882],
       [-0.34060431, -0.24832123, -1.96427616, -0.21333139],
       [-0.11281229, -0.67375361,  0.1084055 ,  0.62525953],
       [-0.08792694, -1.51806396, -0.43298072,  0.81838862]])

**randint**

In [28]:
np.random.randint(low=1,high=100)

76

In [29]:
np.random.randint(low=1,high=100,size=20)

array([48, 33, 19, 68, 94, 27, 31, 21, 91, 92, 95, 77, 13, 45, 97, 90,  3,
       34, 68, 32])

### seed

In [32]:
np.random.seed(40)
np.random.rand(4)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

In [35]:
np.random.seed(40)
np.random.rand(4)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

### List Vs Numpy

In [40]:
x1 = range(size)

In [39]:
size = 10000

In [37]:
x1

range(0, 10000)

In [41]:
y1 = range(size)

In [42]:
%%timeit
[x1[i]*y1[i] for i in range(size)]

2.98 ms ± 72.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
x2 = np.arange(size)
y2 = np.arange(size)

In [44]:
%%timeit
x2*y2

8.89 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [45]:
x2 = np.arange(10)
y2 = np.arange(10)
x2*y2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
'N I E L I T'.split()

['N', 'I', 'E', 'L', 'I', 'T']

##### &&&&